name: Android CI

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          cache-read-only: false

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Clean
        run: ./gradlew clean

      - name: Run KtLint
        run: ./gradlew :app:runKtlint --no-daemon --stacktrace

      - name: Run Checkstyle
        run: ./gradlew :app:runCheckstyle --no-daemon --stacktrace

      - name: Build Debug APK
        run: ./gradlew :app:assembleDebug --no-daemon --stacktrace

      - name: Run unit tests
        run: ./gradlew testDebugUnitTest --no-daemon --stacktrace

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: app/build/outputs/apk/debug/*.apk
